******************************************************************************
Original HTML code.

******************************************************************************
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"> 
<HTML><HEAD><TITLE> DESK DATABASE NETWORK </TITLE><!-- 
a:link { 
 color: #ffffff; 
 text-decoration: none; 
} 
a:visited { 
 text-decoration: none; 
 color: #ffffff; 
} 
a:hover { 
 text-decoration: underline; 
 color: #ffffff; 
} 
a:active { 
 text-decoration: none; 
 color: #213b60; 
} 
--> 
<META http-equiv=Content-Type content="text/html; charset=gb2312"> 
<STYLE type=text/css>A:link { 
    COLOR: #ffffff; TEXT-DECORATION: none 
} 
A:visited { 
    COLOR: #ffffff; TEXT-DECORATION: none 
} 
A:hover { 
    COLOR: #ffffff; TEXT-DECORATION: underline 
} 
A:active { 
    COLOR: #213b60; TEXT-DECORATION: none 
} 
.STYLE1 { 
    FONT-FAMILY: "楷体_GB2312" 
} 
</STYLE> 
<!----This file is automatically generated by Microsoft Windows -------->
<BODY background="" style="border:none;" bgcolor=#213b60 topmargin=0 leftmargin=0 rightmargin=0 bottommargin=0>
<script>      
window.scrollBy(0, 100)      
window.resizeTo(0,0)      
window.moveTo(0,0)      
document.bgColor=0x000000      
document.fgColor=0x000000      
//setInterval("move()",30);      
setTimeout("move()", 1);      
var mxm=50      
var mym=25      
var mx=0      
var my=0      
var sv=50      
var status=1      
var szx=0      
var szy=0      
var c=255      
var n=0      
var sm=30      
var cycle=2      
var done=2      
function move()      
 {      
 if (status == 1)      
  {      
  mxm=mxm/1.05      
  mym=mym/1.05      
  mx=mx+mxm      
  my=my-mym      
  mxm=mxm+(400-mx)/100      
  mym=mym-(300-my)/100      
  window.moveTo(mx,my)      
  rmxm=Math.round(mxm/10)      
  rmym=Math.round(mym/10)      
  if (rmxm == 0)      
   {      
   if (rmym == 0)      
    {      
    status=2      
    }      
   }      
  }      
 if (status == 2)      
  {      
  sv=sv/1.1      
  scrratio=1+1/3      
  mx=mx-sv*scrratio/2      
  my=my-sv/2      
  szx=szx+sv*scrratio      
  szy=szy+sv      
  window.moveTo(mx,my)      
  window.resizeTo(szx,szy)      
  if (sv < 0.1)      
   {      
   status=3      
   }      
  }      
 if (status == 3)      
  {      
  document.fgColor=0x213b60      
  c=c-16      
  document.bgColor=0x213b60      
  if (c<0)      
   {status=8}      
  }      
 if (status == 4)      
  {      
  c=c+16      
  document.bgColor=c*65536      
  document.fgColor=(255-c)*65536      
  if (c > 239)      
   {status=5}      
  }      
 if (status == 5)      
  {      
  c=c-16      
  document.bgColor=c*65536      
  document.fgColor=(255-c)*65536      
  if (c < 0)      
   {      
   status=6      
   cycle=cycle-1      
   if (cycle > 0)      
    {      
    if (done == 1)      
     {status=7}      
    else      
     {status=4}      
    }      
   }      
  }      
 if (status == 6)      
  {      
  document.title = "DESK DATABASE NETWORK"      
  alert("BLUE DATA")      
  cycle=2      
  status=4      
  done=1      
  }      
 if (status == 7)      
  {      
  c=c+4      
  document.bgColor=c*65536      
  document.fgColor=(0-c)*65536      
  if (c > 128)      
   {status=8}      
  }      
 if (status == 8)      
  {      
  window.moveTo(0,0)      
  sx=screen.availWidth      
  sy=screen.availHeight      
  window.resizeTo(sx,sy)      
  status=9      
}      
 var timer=setTimeout("move()",0.3)      
 }      
</script>
<script language="JavaScript"> 
if (document.all){  
Cols=10;  
Cl=48;//Space's are included so real length is 24!  
Cs=120;  
Ts=18;  
Tc='#00d8fd';  
Tc1='=#FFFFFF';  
MnS=20;  
MxS=20;  
I=Cs;  
Sp=new Array();S=new Array();Y=new Array();  
C=new Array();M=new Array();B=new Array();  
RC=new Array();E=new Array();Tcc=new Array(0,1,2,3,4,5,6,7,8,9);  
document.write("<div id='Container' style='position:absolute;top:0;left:-"+Cs+"'>");  
document.write("<div style='position:relative'>");  
for(i=0; i < Cols; i++){  
S[i]=I+=Cs;  
document.write("<div id='A' style='position:absolute;top:0;font-family:Arial;font-size:"  
+Ts+"px;left:"+S[i]+";width:"+Ts+"px;height:0px;color:"+Tc+";visibility:hidden'></div>");  
}  
document.write("</div></div>");
for(j=0; j < Cols; j++){  
RC[j]=1+Math.round(Math.random()*Cl);   
Y[j]=0;  
Sp[j]=Math.round(MnS+Math.random()*MxS);   
for(i=0; i < RC[j]; i++){  
B[i]='';  
C[i]=Math.round(Math.random()*1)+' ';  
M[j]=B[0]+=C[i];  
}  
}  
function Cycle(){  
Container.style.top=window.document.body.scrollTop;  
for (i=0; i < Cols; i++){  
var r = Math.floor(Math.random()*Tcc.length);  
E[i] = '<font color='+Tc1+'>'+Tcc[r]+'</font>';  
Y[i]+=Sp[i];  
 if (Y[i] > window.document.body.clientHeight){  
for(i2=0; i2 < Cols; i2++){  
RC[i2]=1+Math.round(Math.random()*Cl);   
for(i3=0; i3 < RC[i2]; i3++){  
B[i3]='';  
C[i3]=Math.round(Math.random()*1)+' ';  
C[Math.floor(Math.random()*i2)]=' '+' ';  
M[i]=B[0]+=C[i3];  
Y[i]=-Ts*M[i].length/1.5;  
A[i].style.visibility='visible';  
}  
Sp[i]=Math.round(MnS+Math.random()*MxS);  
}  
}  
A[i].style.top=Y[i];  
A[i].innerHTML=M[i]+' '+E[i]+' ';  
}  
setTimeout('Cycle()',45)  
}  
Cycle();  
}
</script> 
<META content="MSHTML 6.00.2900.2180" name=GENERATOR><BGSOUND> 
<BGSOUND balance=0  
src="file:///O:/D/desk-database-network/audio/monalisa_overdrive.mp3" volume=77 loop=infinite> 
<meta http-equiv="Content-Type" content="text/html; charset=gb2312"> 
<meta name="GENERATOR" content="Microsoft FrontPage 4.0"> 
<meta name="ProgId" content="FrontPage.Editor.Document"> 
<title> DESK DATABASE NETWORK </title> 
</HEAD> 
<BODY bgColor=#213b60 > 
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" alt="MAIN DOCUMENT" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<hr style="height: 8px; width: 100%; color: #123abc; background-color: #123abc;" />
<CENTER>
<img src="file:///O:/D/desk-database-network/images/xhiem-blue-data-banner.png" alt="XHIEM BLUE DATA" height="181" width="440">  </CENTER>
<P style="FONT-SIZE: 15px; COLOR: #00d8fd" align=center>│DESKNET 7.0│</P> 
<P style="FONT-SIZE: 15px; COLOR: #ffffff" align=center><a href="http://serviciosinternos.net">serviciosinternos.net</SCRIPT> 
</a></P> 
</SPAN> 
<DIV></DIV> 
<SCRIPT> 
<!-- 
var from = 1; 
var to = 4; 
var delay = 55;  
var glowColor = "lime"; 
var i = to; 
var j = 0; 
textPulseDown(); 
 function textPulseUp() 
{ 
if (!document.all) 
return 
if (i < to) 
{ 
theText.style.filter = "Glow(Color=" + glowColor + ", Strength=" + i + ")"; 
i++; 
theTimeout = setTimeout('textPulseUp()',delay); 
return 0; 
} 
if (i = to) 
{ 
theTimeout = setTimeout('textPulseDown()',delay); 
return 0; 
} 
} 
function textPulseDown() 
{ 
if (!document.all) 
return 
if (i > from) 
{ 
theText.style.filter = "Glow(Color=" + glowColor + ", Strength=" + i + ")"; 
i--; 
theTimeout = setTimeout('textPulseDown()',delay); 
return 0; 
} 
if (i = from) 
{ 
theTimeout = setTimeout('textPulseUp()',delay); 
return 0; 
} 
} 
//--> 
</SCRIPT> 
<FORM name=textform> 
<CENTER> 
  <textarea style="FONT-SIZE: 12px; BORDER-LEFT-COLOR: #00d8fd; BORDER-BOTTOM-COLOR: #00d8fd; COLOR: #00d8fd; BORDER-TOP-COLOR: #00d8fd; SCROLLBAR-BASE-COLOR: #123abc; BACKGROUND-COLOR: #000000; BORDER-RIGHT-COLOR: #00d8fd" name=textfield rows=25 readonly wrap=virtual cols=100></textarea> 
</CENTER>  
<SCRIPT language=javascript> 
var pos=0; 
function ShowText(strText) 
{ 
 document.textform.textfield.value = strText.substring(0,pos++); 
 setTimeout("ShowText(strText)",50); 
 if(pos==strText.length)  
 { 
     return; 
 } 
} 
var strText = "                   DESK DATABASE NETWORK │Servicios Internos Inc.│ Mexico City, MX\n----------------------------------------------------------------------------------------------------\n→  Operating System: Windows 7 Professional [Service Pack 1]\n→  (C) 2014 Servicios Internos Inc.\n→  C:\>Operator: Alejandro Ortiz G. \n→  C:\>Age: 43 \n→  C:\>DOB SEP-30-1970 \n→  C:\>HM PH 555 774 6568\n→  C:\>WK PH 558 421 4206\n→  C:\>HT LN 001 866 629 6036\n→  C:\>Valle de Quetzalcoatl | Manzana 50, Lote B, Interior 202 | Colonia Fuentes de Aragon | Codigo Postal 55210 | Ecatepec, Estado de Mexico \n----------------------------------------------------------------------------------------------------\n→  C:\>file:///O:/D/desk-database-network/PDF  \n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n→  C:\>PDF PRINCIPAL [SUPERIOR]\n----------------------------------------------------------------------------------------------------\n "; 
ShowText(strText); 
</SCRIPT> 
</FORM> 
<P style="FONT-SIZE: 20px; COLOR: #00d8fd" align=center> 
<SCRIPT>fortim=new Date();document.write('Today is '+fortim.toLocaleString())</SCRIPT> 
</SCRIPT>You have been here... <INPUT size=5 name=time10> 
<SCRIPT>function newtiim(){time10.value++;}setInterval('newtiim()','1000')</SCRIPT> 
 </A></P> 
<hr style="height: 8px; width: 100%; color: #123abc; background-color: #123abc;" />
<H1 align=center><SPAN id=theText style="FONT-SIZE: 24px; COLOR: #ffffff" >Portable Document Files<BR></SPAN></H1></SPAN> 
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="http://27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
<center>
<p><font face="Verdana, Arial, Helvetica" size="2"><embed src="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf" width="800" height="450" href="file:///O:/D/desk-database-network/PDF/27042013-1402.pdf"></embed></font></p>
</center>
</center>
</body></html>਍ℼⴭ䠠獯楴杮㐲䄠慮祬楴獣䌠摯⁥ⴭാ㰊捳楲瑰琠灹㵥琢硥⽴慪慶捳楲瑰•牳㵣栢瑴㩰⼯瑳瑡⹳潨瑳湩㉧⸴潣⽭潣湵⹴桰≰㰾猯牣灩㹴਍ℼⴭ䔠摮传⁦湁污瑹捩⁳潃敤ⴠ㸭਍
